# This is a basic workflow to help you get started with Actions

name: Health Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - run: |
        echo "Checking endpoint"
        curl https://openhackvs44eql7userprofile-staging.azurewebsites.net/api/healthcheck/user

    - name: GitHub Script
      uses: actions/github-script@v3.0.0
      with:
        # The script to run
        script: var x = 1;
            
        # The GitHub token used to create an authenticated client
        # github-token: # optional, default is ${{ github.token }}
        # Whether to tell the GitHub client to log details of its requests
        debug: true # optional
        # An optional user-agent string
        # user-agent: # optional, default is actions/github-script
        # A comma-separated list of API previews to accept
        # previews: # optional
        # Either "string" or "json" (default "json")—how the result will be encoded
        # result-encoding: # optional, default is json
